#!/bin/bash
#
# Git pre-commit hook that runs the CI-aligned checks.
# This file is used when git hooks are configured via: git config core.hooksPath .githooks
#
# To skip this hook, use: git commit --no-verify
# To run tests as well, use: RUN_TESTS=1 git commit
# To run doc check as well, use: RUN_DOC=1 git commit

ROOT=$(git rev-parse --show-toplevel)
exec "$ROOT/scripts/pre-commit"
