
//! Autogenerated weights for `pallet_zkhe`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: 2025-11-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Amars-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/confidential-asset-hub/confidential_asset_hub.compact.compressed.wasm
// --pallet
// pallet_zkhe
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/zkhe/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_zkhe`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::pallet::WeightInfo for WeightInfo<T> {
	/// Storage: `Zkhe::PublicKey` (r:2 w:0)
	/// Proof: `Zkhe::PublicKey` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// Storage: `Zkhe::AvailableBalanceCommit` (r:1 w:1)
	/// Proof: `Zkhe::AvailableBalanceCommit` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Zkhe::PendingBalanceCommit` (r:1 w:1)
	/// Proof: `Zkhe::PendingBalanceCommit` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Zkhe::NextPendingDepositId` (r:1 w:1)
	/// Proof: `Zkhe::NextPendingDepositId` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Zkhe::PendingDeposits` (r:0 w:1)
	/// Proof: `Zkhe::PendingDeposits` (`max_values`: None, `max_size`: Some(168), added: 2643, mode: `MaxEncodedLen`)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `340`
		//  Estimated: `6168`
		// Minimum execution time: 6_405_000_000 picoseconds.
		Weight::from_parts(6_535_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6168))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Zkhe::PublicKey` (r:1 w:0)
	/// Proof: `Zkhe::PublicKey` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	/// Storage: `Zkhe::AvailableBalanceCommit` (r:1 w:1)
	/// Proof: `Zkhe::AvailableBalanceCommit` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Zkhe::PendingBalanceCommit` (r:1 w:1)
	/// Proof: `Zkhe::PendingBalanceCommit` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Zkhe::PendingDeposits` (r:1 w:1)
	/// Proof: `Zkhe::PendingDeposits` (`max_values`: None, `max_size`: Some(168), added: 2643, mode: `MaxEncodedLen`)
	fn accept_pending() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `475`
		//  Estimated: `3633`
		// Minimum execution time: 11_755_000_000 picoseconds.
		Weight::from_parts(12_083_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3633))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Estimated as accept_pending + transfer (chained operations)
	fn transfer_from_available() -> Weight {
		// accept_pending weight + transfer weight
		Weight::from_parts(12_083_000_000 + 6_535_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6168 + 3633))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(7))
	}
}
