
//! Autogenerated weights for `pallet_confidential_assets`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: 2025-11-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Amars-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/confidential-asset-hub/confidential_asset_hub.compact.compressed.wasm
// --pallet
// pallet_confidential_assets
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/confidential-assets/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_confidential_assets`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::pallet::WeightInfo for WeightInfo<T> {
	/// Storage: `Zkhe::PublicKey` (r:0 w:1)
	/// Proof: `Zkhe::PublicKey` (`max_values`: None, `max_size`: Some(114), added: 2589, mode: `MaxEncodedLen`)
	fn set_public_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Delegates to pallet_zkhe::transfer - use backend weight + small overhead
	fn confidential_transfer() -> Weight {
		// Backend transfer (~6.5s) + overhead
		Weight::from_parts(6_600_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6168))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Delegates to pallet_zkhe::transfer - use backend weight + small overhead
	fn confidential_transfer_from() -> Weight {
		// Backend transfer (~6.5s) + overhead + ACL checks
		Weight::from_parts(6_650_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6168))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Transfer + external call overhead (estimated)
	fn confidential_transfer_and_call() -> Weight {
		Weight::from_parts(6_800_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6168))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Transfer from + external call overhead (estimated)
	fn confidential_transfer_from_and_call() -> Weight {
		Weight::from_parts(6_850_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6168))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Disclose amount - lightweight decryption check
	fn disclose_amount() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(Weight::from_parts(0, 2589))
			.saturating_add(T::DbWeight::get().reads(1))
	}
}
